name: Create Comment

on:
  issues:
    types: [assigned]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello ${{ github.event.issue.user.login }}, please add this event to your calendar.

            [Add to Google Calendar](https://www.google.com/calendar/render?action=TEMPLATE&text=Meeting&dates=20230101T120000Z/20230101T130000Z&details=Description%20of%20the%20event&location=Office)

          emoji: '+1'
