name: Create Comment

on:
  issues:
    types: [assigned]

jobs:
  create-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Create comment
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'create-comment'
          token: ${{ secrets.GITHUB_TOKEN }}
          issue-number: ${{ github.event.issue.number }}
          body: |
            Hello ${{ github.event.issue.user.login }}.

            你好 ${{ github.event.issue.user.login }}。巴拉巴拉。
          emoji: '+1'
