name: GitEmote

on:
  pull_request:
    types:
      - opened

jobs:
  gitemote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
      - name: Install Specific NPM Packages
        run: npm install @actions/core @actions/github
        

      - name: PR emote generator
        uses: lingeorge88/hello-world-javascript-action@v2.0
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# comment for test 33311231232112