name: GitEmote

on:
  pull_request:
    types:
      - opened

jobs:
  gitemote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install third-party action dependencies
        run: npm install
        
      - name: PR emote generator
        uses: rcmtcristian/gitemote@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# comment for test 333