name: GitEmote

on:
  pull_request:
    types:
      - opened

jobs:
  gitemote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Run GitEmote
        uses: rcmtcristian/gitemote@main
        with:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        #  comment for testing purposes