name: GitEmote

on:
  pull_request:
    types:
      - opened

jobs:
  gitemote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      
      - name: PR emote generator
        uses: lingeorge88/gitemotePR_GL@main
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# testing sticker for PR with refactor key word in title