name: GitEmote

on:
  pull_request:
    types:
      - opened

jobs:
  gitemote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: PR emote generator
        uses: lingeorge88/hello-world-javascript-action@v1.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
# comment for test 333112312321