name: GitEmote

on:
  pull_request:
    types:
      - opened

jobs:
  gitemote:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: PR emote generator
        uses: rcmtcristian/gitemote@Community
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}